networks:
  default:
    name: proxy-net
    external: true
  
volumes:
  db-data:
    name: erp-db-data
  redis-queue-data:
    name: erp-redis-queue-data
  sites:
    name: erp-sites

services:
  backend:
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  configurator:
    env_file:
      - .env
    labels:
      - "traefik.enable=false"
    command:
    - |
      ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    entrypoint:
    - bash
    - -c
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE}
      REDIS_QUEUE: ${REDIS_QUEUE}
      SOCKETIO_PORT: ${SOCKETIO_PORT}
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  db:
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
      ]
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      default: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  frontend:
    env_file:
      - .env
    command:
    - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: ${BACKEND}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE}
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT}
      SOCKETIO: ${SOCKETIO}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE}
    image: frappe/erpnext:v15.84.0
    labels:
      traefik.enable: "true"
      traefik.http.routers.frontend-http.entrypoints: websecure
      traefik.http.routers.frontend-http.rule: Host(`${FRONTEND_HOST_1}`) || Host(`${FRONTEND_HOST_2}`)
      traefik.http.routers.frontend-http.tls.certresolver: letsencrypt
      traefik.http.services.frontend.loadbalancer.server.port: "8080"
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-long:
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    command:
    - bench
    - worker
    - --queue
    - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  queue-short:
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    command:
    - bench
    - worker
    - --queue
    - short,default
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  redis-cache:
    labels:
      - "traefik.enable=false"
    image: redis:6.2-alpine
    networks:
      default: null
  redis-queue:
    labels:
      - "traefik.enable=false"
    image: redis:6.2-alpine
    networks:
      default: null
    volumes:
    - type: volume
      source: redis-queue-data
      target: /data
      volume: {}
  scheduler:
    labels:
      - "traefik.enable=false"
    env_file:
      - .env
    command:
    - bench
    - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}
  websocket:
    env_file:
      - .env
    labels:
      - "traefik.enable=false"
    command:
    - node
    - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.84.0
    networks:
      default: null
    platform: linux/amd64
    pull_policy: always
    volumes:
    - type: volume
      source: sites
      target: /home/frappe/frappe-bench/sites
      volume: {}

x-backend-defaults:
  depends_on:
    configurator:
      condition: service_completed_successfully
  image: frappe/erpnext:v15.84.0
  pull_policy: always
  volumes:
  - sites:/home/frappe/frappe-bench/sites
x-customizable-image:
  image: frappe/erpnext:v15.84.0
  pull_policy: always
x-depends-on-configurator:
  depends_on:
    configurator:
      condition: service_completed_successfully
