version: '3.8'
services:
  # Infrastructure
  reverse-proxy:
    extends:
      file: ./infrastructure/docker-compose.yml
      service: reverse-proxy
  auth:
    extends:
      file: ./infrastructure/docker-compose.yml
      service: auth
  # Services
  erpnext:
    extends:
      file: ./services/erpnext/docker-compose.yml
      service: erpnext
  nextcloud:
    extends:
      file: ./services/nextcloud/docker-compose.yml
      service: nextcloud
  openproject:
    extends:
      file: ./services/openproject/docker-compose.yml
      service: openproject
  # Products
  egrist:
    extends:
      file: ./products/egrist/docker-compose.yml
      service: egrist
  galea:
    extends:
      file: ./products/galea/docker-compose.yml
      service: galea
networks:
  proxy-net:
    external: true
