## Traefik v3 configuration (compatible with v2 syntax, review docs for breaking changes)
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG # Increased log level for maximum verbosity
  format: common

api:
  dashboard: true
  insecure: false # Disable insecure dashboard in production

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

# certificatesResolvers:
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json
      email: aman.soni@egrist.org
      keyType: RSA4096
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    remove-www:
      redirectRegex:
        regex: ^https?://www\.(.*)
        replacement: https://${1}
        permanent: true
  routers:
    http-to-https:
      entryPoints:
        - web
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - redirect-to-https
      service: noop@internal
    remove-www:
      entryPoints:
        - websecure
      rule: "HostRegexp(`www.{host:.+}`)"
      middlewares:
        - remove-www
      service: noop@internal

