## Traefik v3 configuration (compatible with v2 syntax, review docs for breaking changes)
global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO # Increased log level for more verbose logging
  format: common

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

# certificatesResolvers:
#   selfsigned:
#     acme:
#       email: admin@example.com
#       storage: /etc/traefik/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       keyType: RSA4096
#       httpChallenge:
#         entryPoint: web

tls:
  certificates:
    - certFile: "/etc/traefik/certs/local-cert.pem"
      keyFile: "/etc/traefik/certs/local-key.pem"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

