version: '3'

services:
  registry:
    image: registry:2
    container_name: private-registry
    ports:
      - "5000:5000"
    restart: always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_HTTP_ADDR: :5000
      # Uncomment for authentication
      # REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    networks:
      - registry-net

networks:
  registry-net:
