volumes:
  grafana_data:
  kuma-data:

networks:
  proxy-net:
    external: true
  internal-net:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - kuma-data:/app/data
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`monitor.sublimecyb.org`)"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.routers.kuma.tls.certresolver=letsencrypt"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - internal-net
      - proxy-net

  alloy:
    image: grafana/alloy:latest
    command: --config.file=/etc/alloy/alloy-config.yml
    volumes:
      - ./config/alloy-config.yml:/etc/alloy/alloy-config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal-net
      - proxy-net

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`logs.sublimecyb.org`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - internal-net
      - proxy-net


