networks:
  proxy-net: # Public-facing network for Traefik to connect to services
    external: true # Docker Compose will create this
  default:
    external: false
    name: analytics-net

volumes:
  db:
  matomo:

services:
  db:
    env_file:
      - .env
    image: mariadb:lts
    command: --max-allowed-packet=64MB
    restart: always
    networks:
      - default
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_DISABLE_UPGRADE_BACKUP=${MARIADB_DISABLE_UPGRADE_BACKUP}
      - MARIADB_INITDB_SKIP_TZINFO=${MARIADB_INITDB_SKIP_TZINFO}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}

  app:
    env_file:
      - .env
    image: matomo:fpm-alpine
    restart: always
    networks:
      - default
    depends_on:
      - db
    volumes:
      # - ./config:/var/www/html/config:z
      # - ./logs:/var/www/html/logs:z
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_ADAPTER=${MATOMO_DATABASE_ADAPTER}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DATABASE_DBNAME}
      - MATOMO_DATABASE_HOST=${MATOMO_DATABASE_HOST}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DATABASE_PASSWORD}
      - MATOMO_DATABASE_TABLES_PREFIX=${MATOMO_DATABASE_TABLES_PREFIX}
      - MATOMO_DATABASE_USERNAME=${MATOMO_DATABASE_USERNAME}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}

  web:
    image: nginx:alpine-slim
    env_file:
      - .env
    restart: always
    networks:
      - default
      - proxy-net
    depends_on:
      - app
    volumes:
      - matomo:/var/www/html:z,ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    # ports:
    #   - 8080:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.analytics.rule=Host(`${ANALYTICS_HOST}`)
      # - traefik.http.routers.analytics.tls=true
      - traefik.http.routers.analytics.entrypoints=web
      - traefik.http.services.analytics.loadbalancer.server.port=80