version: '3.9'

services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    networks:
      - proxy-net
      - internal-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`app.sublimecyb.org`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.services.frontend.loadbalancer.server.port=8000
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://api.sublimecyb.org
    ports:
      - "8000:8000"

  api:
    build: ./api
    networks:
      - proxy-net
      - internal-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.sublimecyb.org`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.services.api.loadbalancer.server.port=8000
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AUTH_SERVER_URL=http://auth.sublimecyb.org/realms/galea
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=galea_user
      - PG_PASSWORD=galea_password
      - PG_DATABASE=galea_db

networks:
  proxy-net:
    external: true
  internal-net:
    external: true

volumes:
  frontend_node_modules:
