networks:
  proxy-net: # Public-facing network for Traefik to connect to services
    external: true # Docker Compose will create this
  internal-net: # Internal private network
    external: true

volumes:
  keycloak_data:
  keycloak_db_data:
  portainer_data:

services:
  reverse-proxy:
    container_name: reverse-proxy
    env_file:
      - .env
    image: traefik:v3.5 # Upgraded to Traefik v3
    # Optional: enable access logs for Traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--accesslog.format=json"
    # Optional: enable access logs for Traefik
    # For HTTPS locally, you'd need self-signed certs config here
    # For now, we'll focus on HTTP on port 80
    ports:
      - "80:80"    # The HTTP port
      - "443:443"  # The HTTPS port (even if not fully configured yet)
      - "8080:8080" # The Traefik dashboard port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # So Traefik can see other containers
      # - ./traefik/certs:/etc/traefik/certs:ro # For local HTTPS certs if you generate them
      # - ./traefik:/etc/traefik:ro # Mount the whole traefik config directory
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/certs/acme.json:/letsencrypt/acme.json
    networks:
      - proxy-net # Traefik must be on the same network as the services it manages
      - internal-net   # Attach to internal network for routing to all services
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"
        # Restrict dashboard access in production (see Traefik docs for auth middleware)
      - "traefik.http.middlewares.http-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=http-to-https,redirect-to-https"
      # Global HTTP to HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{any:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"        
    environment:
      - TRAEFIK_DASHBOARD_HOST=traefik.sublimecyb.org

  # --- Keycloak Authentication Service ---
  auth:
    container_name: auth
    image: quay.io/keycloak/keycloak:22.0.4
    env_file:
      - .env
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - KC_PROXY=${KC_PROXY}
      - KC_HOSTNAME_STRICT_HTTPS=${KC_HOSTNAME_STRICT_HTTPS}
      - KC_HOSTNAME_STRICT_ORIGIN=${KC_HOSTNAME_STRICT_ORIGIN}
      - KC_HOSTNAME_URL=${KC_HOSTNAME_URL}
    command: start-dev # For development mode, not for production
    networks:
      - proxy-net
      - internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`${AUTH_HOST}`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.auth.loadbalancer.server.port=8080" # Set to actual Keycloak port if different
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Host=auth.sublimecyb.org"
      - "traefik.http.routers.auth.middlewares=keycloak-headers@docker"
    depends_on:
      - keycloak-db
    volumes: # Persist Keycloak data
      - keycloak_data:/opt/keycloak/data

  # --- Keycloak's Database Service ---
  keycloak-db:
    env_file:
      - .env
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - internal-net # Only accessible internally

  portainer:
    image: portainer/portainer-ce:2.35.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
